- name: Update and upgrade apt packages
  become: true
  apt:
    update_cache: true
    upgrade: full
    state: latest
    autoremove: true
    autoclean: true

- name: Install misc. APT packages
  become: true
  apt:
    name: "{{ item }}"
  loop: "{{ apt_package_list }}"
