- name: Install Git
  apt:
    name: git
  become: yes

# TODO: ask for user and email
- name: Copy Git configuration files
  include_tasks: "../general/tasks/copy_with_backup.yaml"
  vars:
    src: '{{ role_path }}/files/.gitconfig'
    dest: '~/.gitconfig'
