- name: Install Tmux
  apt:
    name: tmux
  become: yes

- name: Install Tmux Plugin Manager (tpm)
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm

- name: Copy Tmux configuration files
  include_tasks: "../general/tasks/copy_with_backup.yaml"
  vars:
    src: '{{ role_path }}/files/.tmux.conf'
    dest: '~/.tmux.conf'

# https://github.com/tmux-plugins/tpm/issues/6
- name: Install Tmux plugins
  command: ~/.tmux/plugins/tpm/scripts/install_plugins.sh
  register: output
  changed_when: "'Installing' in output.stdout"
