- name: Install
  hosts: localhost

  roles:
    - role: general
      tags: general
    - role: bash
      tags: bash
    - role: tmux
      tags: tmux
    - role: git
      tags: git
    - role: vscodium
      tags: vscodium
    - role: neovim
      tags: neovim
    - role: firefox
      tags: firefox
    - role: ulauncher
      tags: ulauncher
    - role: fonts
      tags: fonts

  vars:
    apt_package_list:
      - curl
      - fzf
      - npm
      - python3
      - python3-pip
      - wget

    build_root_dir: /usr/src/bryton

    font_file_list:
      # Hack
      - HackNerdFontMono-Bold.ttf
      - HackNerdFontMono-BoldItalic.ttf
      - HackNerdFontMono-Italic.ttf
      - HackNerdFontMono-Regular.ttf
      # UbuntuMonoNerdFontMono
      - UbuntuMonoNerdFontMono-Bold.ttf
      - UbuntuMonoNerdFontMono-BoldItalic.ttf
      - UbuntuMonoNerdFontMono-Italic.ttf
      - UbuntuMonoNerdFontMono-Regular.ttf

    firefox_extension_list:
      - https://addons.mozilla.org/fr/firefox/addon/multi-account-containers/
      - https://addons.mozilla.org/fr/firefox/addon/ublock-origin/
      - https://addons.mozilla.org/fr/firefox/addon/wappalyzer/
      - https://addons.mozilla.org/fr/firefox/addon/duckduckgo-for-firefox/
      - https://addons.mozilla.org/fr/firefox/addon/consent-o-matic/
      - https://addons.mozilla.org/fr/firefox/addon/clearurls/

    vscodium_extension_list:
      - mvllow.rose-pine
      - MS-CEINTL.vscode-language-pack-fr
      - PKief.material-icon-theme
      - PKief.material-product-icons
      - vscodevim.vim
      - VSpaceCode.whichkey
